import Head from 'next/head'
// import Image from 'next/image'
import { DM_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Center, Flex, Image,Box,Text, Spacer, Divider } from '@chakra-ui/react'
import { getChartData } from '@/lib/chart'

const dm = DM_Sans({weight:['400','700'], subsets: ['latin'] })

export default function Home({chartData}) {
  // const asd = getChartData()
  let maxValue = 0;
  chartData.map(item =>{
    if(item.amount > maxValue) maxValue=item.amount
  })
  return (
    <>
      <Head>
        <title>Expenses Chart FrontMentor.io</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className={dm.className}>
        <Center bg="brand.orange" w='100vw' h='100vh'>
          <Box width='50vw' maxWidth='400px' minW='350px'>
            <Flex bg="brand.softRed" color="white" px='30px' py='20px' borderRadius='15px'>
              <Box >
                <Text fontSize='18px' color="white">My Balance</Text>
                <Text fontSize='35px'>$921.48</Text>
              </Box>
              <Spacer />
              <Center>
                <Image src="/images/logo.svg" alt='logo' />
              </Center>
            </Flex>
            <Box bg="white" borderRadius='15px' p='20px 30px' mt="30px" height='25vw' minH='400px' maxH='320px'>
              <Text fontSize='20px' color='brand.darkBrown' fontWeight='bold'>Spending - Last 7 days</Text>
              <Flex justifyContent='space-between' fontSize='12px' 
                    color='brand.mediumBrown' height='150px' mt='30px'>
              {
                chartData.map(item=>{
                  return <Flex flexDir='column' justifyContent='flex-end'>
                    <Box w='30px' bg={item.amount == maxValue ? "brand.cyan" : "brand.softRed"} borderRadius='5px'
                        h={item.amount == maxValue ? '100%' : `calc(${item.amount}/${maxValue} * 100%)`}
                        _hover={{opacity:'0.8'}}></Box>
                    <Text textAlign='center'>{item.day}</Text>
                  </Flex> 
                })
              }
               
              </Flex>
              
              <Divider bg="brand.cream" mt='30px' />
              <Text fontSize='18px' mt='30px' mb='-7px' color="brand.mediumBrown">Total this month</Text>
              <Flex>
                <Text fontSize='35px' fontWeight='bold' color="brand.darkBrown"> $478.33</Text>
                <Spacer />
                <Box fontSize='18px' >
                  <Text fontWeight='bold' color="brand.darkBrown" fontSize='18px' textAlign='right'>+2.4%</Text>
                  <Text color="brand.mediumBrown" fontSize='18px'>from last month</Text>
                </Box>
              </Flex>
            </Box>
            
          </Box>
          
        </Center>
      </main>
    </>
  )
}

export async function getStaticProps(){
  const chartData =await getChartData();
  return {
    props: {
      chartData,
    }
  }
}
