import Head from 'next/head'
// import Image from 'next/image'
import { DM_Sans } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Center, Flex, Image,Box,Text, Spacer, Divider } from '@chakra-ui/react'
import { getChartData } from '@/lib/chart'

const dm = DM_Sans({weight:['400','700'], subsets: ['latin'] })

export default function Home({chartData}) {
  // const asd = getChartData()
  return (
    <>
      <Head>
        <title>Expenses Chart FrontMentor.io</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className={dm.className}>
        <Center bg="brand.orange" w='100vw' h='100vh'>
          <Box width='40vw'>
            <Flex bg="brand.softRed" color="white" px='30px' py='20px' borderRadius='15px'>
              <Box >
                <Text fontSize='12px'>My Balance</Text>
                <Text fontSize='18px'>$921.48</Text>
              </Box>
              <Spacer />
              <Center>
                <Image src="/images/logo.svg" alt='logo' />
              </Center>
            </Flex>
            <Box bg="white" borderRadius='15px' p='20px 30px' mt="20px">
              <Text fontSize='18px' color='brand.darkBrown'>Spending - Last 7 days</Text>
              <Flex justifyContent='space-between' fontSize='12px' color='brand.mediumBrown'>
                <Text>mon</Text>
                <Text>tue</Text>
                <Text>wed</Text>
                <Text>thu</Text>
                <Text>fri</Text>
                <Text>sat</Text>
                <Text>sun</Text>
              </Flex>
              {
                chartData.map(item=>{
                  return <Text>{item.day} {item.amount}</Text>
                })
              }
              <Divider />
              <Text fontSize='12px'>Total this month</Text>
              <Flex>
                <Text fontSize='18px'> $478.33</Text>
                <Spacer />
                <Box fontSize='12px'>
                  <Text>+2.4%</Text>
                  <Text>from last month</Text>
                </Box>
              </Flex>
            </Box>
            
          </Box>
          
        </Center>
      </main>
    </>
  )
}

export async function getStaticProps(){
  const chartData =await getChartData();
  return {
    props: {
      chartData,
    }
  }
}
